name: phpunit

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4

    - name: Compose setup
      run: |
        composer validate
        composer check-platform-reqs
        composer dump-autoload
        composer install --no-interaction

    - name: Test the code
      run: composer exec phpunit
